package com.freeftp.core.testing

import java.nio.file.Files
import java.nio.file.Path
import java.security.PublicKey
import java.util.Base64
import java.util.concurrent.TimeUnit
import net.schmizz.sshj.common.Buffer

/**
 * Real OpenSSH key pairs, generated by `ssh-keygen`.
 *
 * Users paste keys that `ssh-keygen` produced, in the formats `ssh-keygen` produces —
 * including the OpenSSH v1 container that is not PEM at all. Generating them with the
 * real tool is the only way to be sure the client parses what people actually have.
 */
object SshKeyFixtures {

    data class KeyPairFixture(
        val privateKeyText: String,
        val publicKey: PublicKey,
        val passphrase: String?,
    )

    fun isAvailable(): Boolean = runCatching {
        ProcessBuilder("ssh-keygen", "-?")
            .redirectErrorStream(true)
            .start()
            .also { it.waitFor(10, TimeUnit.SECONDS) }
        true
    }.getOrDefault(false)

    /**
     * Generates a key pair of [type] (`ed25519`, `rsa`, ...) in [directory].
     * A non-null [passphrase] produces an encrypted private key.
     */
    fun generate(directory: Path, type: String, passphrase: String? = null): KeyPairFixture {
        val target = directory.resolve("id_$type${passphrase?.let { "_enc" } ?: ""}")
        Files.deleteIfExists(target)
        Files.deleteIfExists(directory.resolve("${target.fileName}.pub"))
        val process = ProcessBuilder(
            "ssh-keygen",
            "-q",
            "-t", type,
            "-N", passphrase ?: "",
            "-C", "freeftp-test",
            "-f", target.toString(),
        ).redirectErrorStream(true).start()
        val output = process.inputStream.bufferedReader().readText()
        check(process.waitFor(60, TimeUnit.SECONDS)) { "ssh-keygen timed out" }
        check(process.exitValue() == 0) { "ssh-keygen failed: $output" }

        return KeyPairFixture(
            privateKeyText = Files.readString(target),
            publicKey = parseOpenSshPublicKey(Files.readString(directory.resolve("${target.fileName}.pub"))),
            passphrase = passphrase,
        )
    }

    /** Decodes an `ssh-ed25519 AAAA... comment` line into a [PublicKey]. */
    fun parseOpenSshPublicKey(line: String): PublicKey {
        val blob = line.trim().split(Regex("\\s+"))[1]
        return Buffer.PlainBuffer(Base64.getDecoder().decode(blob)).readPublicKey()
    }
}
