#!/usr/bin/env python3
"""Regenerates the launcher icon resources from the source SVG.

Kept in the repo so the icon can be rebuilt when the artwork changes, rather than
being a pile of binaries nobody can reproduce.

    python3 tools/generate-launcher-icon.py art/FreeFTP.svg

Needs `cairosvg` (raster output only); the vector drawables are produced from the
SVG path data directly, with no external converter.
"""
import os
import re
import sys

# Adaptive icons are drawn on a 108dp canvas and then masked by the launcher, which
# is free to use a circle. Only the inscribed circle of the central 72dp is certain
# to survive, so the artwork is scaled to sit inside it with a little room to spare.
# Without this the outer strokes of the wordmark are sliced off on round launchers.
SAFE_RADIUS_FRACTION = 36.0 / 108.0
MARGIN = 0.96

RES = "app/src/main/res"
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}


def parse(svg_text):
    """Returns (canvas_size, background_fill, [(path_data, fill_rule), ...])."""
    view_box = re.search(r'viewBox="([\d.\s]+)"', svg_text).group(1).split()
    size = float(view_box[2])
    paths = re.findall(
        r'<path fill="(#[0-9a-fA-F]{6})"[^>]*?d="([^"]+)"[^>]*?(?:fill-rule="(\w+)")?/>',
        svg_text,
    )
    background = next((f for f, _, _ in paths if f.lower() != "#ffffff"), "#000000")
    foreground = [(d, rule or "nonZero") for f, d, rule in paths if f.lower() == "#ffffff"]
    return size, background, foreground


def content_bounds(paths):
    from svgelements import Path

    x0 = y0 = float("inf")
    x1 = y1 = float("-inf")
    for data, _ in paths:
        bx0, by0, bx1, by1 = Path(data).bbox()
        x0, y0, x1, y1 = min(x0, bx0), min(y0, by0), max(x1, bx1), max(y1, by1)
    return x0, y0, x1, y1


def vector_drawable(size, paths, scale, pivot, colour):
    fill_type = {"evenodd": "evenOdd", "nonzero": "nonZero"}
    body = "\n".join(
        f'        <path\n'
        f'            android:fillColor="{colour}"\n'
        f'            android:fillType="{fill_type.get(rule.lower(), "nonZero")}"\n'
        f'            android:pathData="{data}" />'
        for data, rule in paths
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate-launcher-icon.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="{size:.0f}"
    android:viewportHeight="{size:.0f}">
    <group
        android:pivotX="{pivot[0]:.1f}"
        android:pivotY="{pivot[1]:.1f}"
        android:scaleX="{scale:.4f}"
        android:scaleY="{scale:.4f}">
{body}
    </group>
</vector>
"""


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as handle:
        handle.write(text)
    print(f"  wrote {path}")


def main(svg_path):
    svg_text = open(svg_path).read()
    size, background, paths = parse(svg_text)
    x0, y0, x1, y1 = content_bounds(paths)
    centre = ((x0 + x1) / 2, (y0 + y1) / 2)
    half_diagonal = (((x1 - x0) / 2) ** 2 + ((y1 - y0) / 2) ** 2) ** 0.5
    scale = min(1.0, (size * SAFE_RADIUS_FRACTION * MARGIN) / half_diagonal)
    print(f"artwork {x1 - x0:.0f}x{y1 - y0:.0f} in a {size:.0f} canvas -> scale {scale:.3f}")

    write(f"{RES}/drawable/ic_launcher_foreground.xml",
          vector_drawable(size, paths, scale, centre, "#FFFFFF"))
    # The themed-icon layer is tinted by the system, so it carries shape only.
    write(f"{RES}/drawable/ic_launcher_monochrome.xml",
          vector_drawable(size, paths, scale, centre, "#FFFFFF"))
    write(f"{RES}/values/ic_launcher_background.xml",
          '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
          f'    <color name="ic_launcher_background">{background.upper()}</color>\n</resources>\n')

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""
    write(f"{RES}/mipmap-anydpi-v26/ic_launcher.xml", adaptive)

    # Raster fallbacks. These are never masked, so they keep the full-bleed artwork
    # the way it was drawn; they are what tools that cannot read an adaptive icon —
    # F-Droid's listing among them — fall back to.
    import cairosvg

    for density, pixels in DENSITIES.items():
        target = f"{RES}/mipmap-{density}/ic_launcher.png"
        os.makedirs(os.path.dirname(target), exist_ok=True)
        cairosvg.svg2png(url=svg_path, write_to=target, output_width=pixels, output_height=pixels)
        print(f"  wrote {target} ({pixels}px)")

    store = "fastlane/metadata/android/en-US/images/icon.png"
    os.makedirs(os.path.dirname(store), exist_ok=True)
    cairosvg.svg2png(url=svg_path, write_to=store, output_width=512, output_height=512)
    print(f"  wrote {store} (512px)")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "art/FreeFTP.svg")
